-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fmcw_ramp_gen is
generic (
    C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    dac_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dac_stream_TVALID : OUT STD_LOGIC;
    dac_stream_TREADY : IN STD_LOGIC;
    dac_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    dac_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    dac_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    sync_trigger : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of fmcw_ramp_gen is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fmcw_ramp_gen_fmcw_ramp_gen,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.024500,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=135,HLS_SYN_LUT=258,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal min_val : STD_LOGIC_VECTOR (13 downto 0);
    signal max_val : STD_LOGIC_VECTOR (13 downto 0);
    signal step_size : STD_LOGIC_VECTOR (13 downto 0);
    signal enable : STD_LOGIC_VECTOR (0 downto 0);
    signal current_val : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal dac_stream_TDATA_blk_n : STD_LOGIC;
    signal enable_read_read_fu_76_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal enable_read_reg_192 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_fu_179_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln43_reg_206 : STD_LOGIC_VECTOR (13 downto 0);
    signal regslice_both_dac_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal sync_trigger_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal zext_ln43_fu_141_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln43_1_fu_145_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln43_fu_149_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln43_2_fu_155_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln43_fu_159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln49_fu_173_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal dac_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal dac_stream_TVALID_int_regslice : STD_LOGIC;
    signal dac_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dac_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dac_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dac_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dac_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dac_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dac_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dac_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dac_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dac_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dac_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fmcw_ramp_gen_s_axi_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        min_val : OUT STD_LOGIC_VECTOR (13 downto 0);
        max_val : OUT STD_LOGIC_VECTOR (13 downto 0);
        step_size : OUT STD_LOGIC_VECTOR (13 downto 0);
        enable : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component fmcw_ramp_gen_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    s_axi_control_s_axi_U : component fmcw_ramp_gen_s_axi_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_s_axi_control_AWVALID,
        AWREADY => s_axi_s_axi_control_AWREADY,
        AWADDR => s_axi_s_axi_control_AWADDR,
        WVALID => s_axi_s_axi_control_WVALID,
        WREADY => s_axi_s_axi_control_WREADY,
        WDATA => s_axi_s_axi_control_WDATA,
        WSTRB => s_axi_s_axi_control_WSTRB,
        ARVALID => s_axi_s_axi_control_ARVALID,
        ARREADY => s_axi_s_axi_control_ARREADY,
        ARADDR => s_axi_s_axi_control_ARADDR,
        RVALID => s_axi_s_axi_control_RVALID,
        RREADY => s_axi_s_axi_control_RREADY,
        RDATA => s_axi_s_axi_control_RDATA,
        RRESP => s_axi_s_axi_control_RRESP,
        BVALID => s_axi_s_axi_control_BVALID,
        BREADY => s_axi_s_axi_control_BREADY,
        BRESP => s_axi_s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        min_val => min_val,
        max_val => max_val,
        step_size => step_size,
        enable => enable,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_dac_stream_V_data_V_U : component fmcw_ramp_gen_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dac_stream_TDATA_int_regslice,
        vld_in => dac_stream_TVALID_int_regslice,
        ack_in => dac_stream_TREADY_int_regslice,
        data_out => dac_stream_TDATA,
        vld_out => regslice_both_dac_stream_V_data_V_U_vld_out,
        ack_out => dac_stream_TREADY,
        apdone_blk => regslice_both_dac_stream_V_data_V_U_apdone_blk);

    regslice_both_dac_stream_V_keep_V_U : component fmcw_ramp_gen_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => dac_stream_TVALID_int_regslice,
        ack_in => regslice_both_dac_stream_V_keep_V_U_ack_in_dummy,
        data_out => dac_stream_TKEEP,
        vld_out => regslice_both_dac_stream_V_keep_V_U_vld_out,
        ack_out => dac_stream_TREADY,
        apdone_blk => regslice_both_dac_stream_V_keep_V_U_apdone_blk);

    regslice_both_dac_stream_V_strb_V_U : component fmcw_ramp_gen_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => dac_stream_TVALID_int_regslice,
        ack_in => regslice_both_dac_stream_V_strb_V_U_ack_in_dummy,
        data_out => dac_stream_TSTRB,
        vld_out => regslice_both_dac_stream_V_strb_V_U_vld_out,
        ack_out => dac_stream_TREADY,
        apdone_blk => regslice_both_dac_stream_V_strb_V_U_apdone_blk);

    regslice_both_dac_stream_V_last_V_U : component fmcw_ramp_gen_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xor_ln43_fu_165_p2,
        vld_in => dac_stream_TVALID_int_regslice,
        ack_in => regslice_both_dac_stream_V_last_V_U_ack_in_dummy,
        data_out => dac_stream_TLAST,
        vld_out => regslice_both_dac_stream_V_last_V_U_vld_out,
        ack_out => dac_stream_TREADY,
        apdone_blk => regslice_both_dac_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    sync_trigger_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                sync_trigger_preg <= ap_const_lv1_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    if ((enable = ap_const_lv1_1)) then 
                        sync_trigger_preg <= xor_ln43_fu_165_p2;
                    elsif ((enable_read_read_fu_76_p2 = ap_const_lv1_0)) then 
                        sync_trigger_preg <= ap_const_lv1_0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    current_val_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((enable_read_read_fu_76_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                current_val <= min_val;
            elsif (((enable_read_reg_192 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
                current_val <= select_ln43_reg_206;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                enable_read_reg_192 <= enable;
                select_ln43_reg_206 <= select_ln43_fu_179_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln43_fu_149_p2 <= std_logic_vector(unsigned(zext_ln43_fu_141_p1) + unsigned(zext_ln43_1_fu_145_p1));
    add_ln49_fu_173_p2 <= std_logic_vector(unsigned(current_val) + unsigned(step_size));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, enable, dac_stream_TREADY_int_regslice)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or ((enable = ap_const_lv1_1) and (dac_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_assign_proc : process(enable_read_reg_192, regslice_both_dac_stream_V_data_V_U_apdone_blk, dac_stream_TREADY_int_regslice)
    begin
                ap_block_state2 <= ((regslice_both_dac_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or ((enable_read_reg_192 = ap_const_lv1_1) and (dac_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    dac_stream_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, enable, ap_CS_fsm_state2, enable_read_reg_192, dac_stream_TREADY_int_regslice)
    begin
        if ((((enable_read_reg_192 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_1) and (enable = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            dac_stream_TDATA_blk_n <= dac_stream_TREADY_int_regslice;
        else 
            dac_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dac_stream_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_val),32));
    dac_stream_TVALID <= regslice_both_dac_stream_V_data_V_U_vld_out;

    dac_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state1, enable, ap_block_state1)
    begin
        if (((enable = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            dac_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            dac_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    enable_read_read_fu_76_p2 <= enable;
    icmp_ln43_fu_159_p2 <= "1" when (unsigned(add_ln43_fu_149_p2) < unsigned(zext_ln43_2_fu_155_p1)) else "0";
    select_ln43_fu_179_p3 <= 
        min_val when (xor_ln43_fu_165_p2(0) = '1') else 
        add_ln49_fu_173_p2;

    sync_trigger_assign_proc : process(ap_CS_fsm_state1, enable, enable_read_read_fu_76_p2, xor_ln43_fu_165_p2, ap_block_state1, sync_trigger_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
            if ((enable = ap_const_lv1_1)) then 
                sync_trigger <= xor_ln43_fu_165_p2;
            elsif ((enable_read_read_fu_76_p2 = ap_const_lv1_0)) then 
                sync_trigger <= ap_const_lv1_0;
            else 
                sync_trigger <= sync_trigger_preg;
            end if;
        else 
            sync_trigger <= sync_trigger_preg;
        end if; 
    end process;

    xor_ln43_fu_165_p2 <= (icmp_ln43_fu_159_p2 xor ap_const_lv1_1);
    zext_ln43_1_fu_145_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(step_size),15));
    zext_ln43_2_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(max_val),15));
    zext_ln43_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_val),15));
end behav;
