// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fmcw_ramp_gen_fmcw_ramp_gen,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.024500,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=135,HLS_SYN_LUT=258,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module fmcw_ramp_gen (
        ap_clk,
        ap_rst_n,
        dac_stream_TDATA,
        dac_stream_TVALID,
        dac_stream_TREADY,
        dac_stream_TKEEP,
        dac_stream_TSTRB,
        dac_stream_TLAST,
        sync_trigger,
        s_axi_s_axi_control_AWVALID,
        s_axi_s_axi_control_AWREADY,
        s_axi_s_axi_control_AWADDR,
        s_axi_s_axi_control_WVALID,
        s_axi_s_axi_control_WREADY,
        s_axi_s_axi_control_WDATA,
        s_axi_s_axi_control_WSTRB,
        s_axi_s_axi_control_ARVALID,
        s_axi_s_axi_control_ARREADY,
        s_axi_s_axi_control_ARADDR,
        s_axi_s_axi_control_RVALID,
        s_axi_s_axi_control_RREADY,
        s_axi_s_axi_control_RDATA,
        s_axi_s_axi_control_RRESP,
        s_axi_s_axi_control_BVALID,
        s_axi_s_axi_control_BREADY,
        s_axi_s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] dac_stream_TDATA;
output   dac_stream_TVALID;
input   dac_stream_TREADY;
output  [3:0] dac_stream_TKEEP;
output  [3:0] dac_stream_TSTRB;
output  [0:0] dac_stream_TLAST;
output  [0:0] sync_trigger;
input   s_axi_s_axi_control_AWVALID;
output   s_axi_s_axi_control_AWREADY;
input  [C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_s_axi_control_AWADDR;
input   s_axi_s_axi_control_WVALID;
output   s_axi_s_axi_control_WREADY;
input  [C_S_AXI_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_s_axi_control_WDATA;
input  [C_S_AXI_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_s_axi_control_WSTRB;
input   s_axi_s_axi_control_ARVALID;
output   s_axi_s_axi_control_ARREADY;
input  [C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_s_axi_control_ARADDR;
output   s_axi_s_axi_control_RVALID;
input   s_axi_s_axi_control_RREADY;
output  [C_S_AXI_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_s_axi_control_RDATA;
output  [1:0] s_axi_s_axi_control_RRESP;
output   s_axi_s_axi_control_BVALID;
input   s_axi_s_axi_control_BREADY;
output  [1:0] s_axi_s_axi_control_BRESP;
output   interrupt;

reg[0:0] sync_trigger;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [13:0] min_val;
wire   [13:0] max_val;
wire   [13:0] step_size;
wire   [0:0] enable;
reg   [13:0] current_val;
reg    dac_stream_TDATA_blk_n;
wire   [0:0] enable_read_read_fu_76_p2;
wire    ap_CS_fsm_state2;
reg   [0:0] enable_read_reg_192;
wire   [0:0] xor_ln43_fu_165_p2;
wire   [13:0] select_ln43_fu_179_p3;
reg   [13:0] select_ln43_reg_206;
wire    regslice_both_dac_stream_V_data_V_U_apdone_blk;
reg    ap_block_state2;
reg    ap_block_state1;
reg   [0:0] sync_trigger_preg;
wire   [14:0] zext_ln43_fu_141_p1;
wire   [14:0] zext_ln43_1_fu_145_p1;
wire   [14:0] add_ln43_fu_149_p2;
wire   [14:0] zext_ln43_2_fu_155_p1;
wire   [0:0] icmp_ln43_fu_159_p2;
wire   [13:0] add_ln49_fu_173_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire   [31:0] dac_stream_TDATA_int_regslice;
reg    dac_stream_TVALID_int_regslice;
wire    dac_stream_TREADY_int_regslice;
wire    regslice_both_dac_stream_V_data_V_U_vld_out;
wire    regslice_both_dac_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_dac_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_dac_stream_V_keep_V_U_vld_out;
wire    regslice_both_dac_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_dac_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_dac_stream_V_strb_V_U_vld_out;
wire    regslice_both_dac_stream_V_last_V_U_apdone_blk;
wire    regslice_both_dac_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_dac_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 current_val = 14'd0;
#0 sync_trigger_preg = 1'd0;
end

fmcw_ramp_gen_s_axi_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_S_AXI_CONTROL_DATA_WIDTH ))
s_axi_control_s_axi_U(
    .AWVALID(s_axi_s_axi_control_AWVALID),
    .AWREADY(s_axi_s_axi_control_AWREADY),
    .AWADDR(s_axi_s_axi_control_AWADDR),
    .WVALID(s_axi_s_axi_control_WVALID),
    .WREADY(s_axi_s_axi_control_WREADY),
    .WDATA(s_axi_s_axi_control_WDATA),
    .WSTRB(s_axi_s_axi_control_WSTRB),
    .ARVALID(s_axi_s_axi_control_ARVALID),
    .ARREADY(s_axi_s_axi_control_ARREADY),
    .ARADDR(s_axi_s_axi_control_ARADDR),
    .RVALID(s_axi_s_axi_control_RVALID),
    .RREADY(s_axi_s_axi_control_RREADY),
    .RDATA(s_axi_s_axi_control_RDATA),
    .RRESP(s_axi_s_axi_control_RRESP),
    .BVALID(s_axi_s_axi_control_BVALID),
    .BREADY(s_axi_s_axi_control_BREADY),
    .BRESP(s_axi_s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .min_val(min_val),
    .max_val(max_val),
    .step_size(step_size),
    .enable(enable),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fmcw_ramp_gen_regslice_both #(
    .DataWidth( 32 ))
regslice_both_dac_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dac_stream_TDATA_int_regslice),
    .vld_in(dac_stream_TVALID_int_regslice),
    .ack_in(dac_stream_TREADY_int_regslice),
    .data_out(dac_stream_TDATA),
    .vld_out(regslice_both_dac_stream_V_data_V_U_vld_out),
    .ack_out(dac_stream_TREADY),
    .apdone_blk(regslice_both_dac_stream_V_data_V_U_apdone_blk)
);

fmcw_ramp_gen_regslice_both #(
    .DataWidth( 4 ))
regslice_both_dac_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(dac_stream_TVALID_int_regslice),
    .ack_in(regslice_both_dac_stream_V_keep_V_U_ack_in_dummy),
    .data_out(dac_stream_TKEEP),
    .vld_out(regslice_both_dac_stream_V_keep_V_U_vld_out),
    .ack_out(dac_stream_TREADY),
    .apdone_blk(regslice_both_dac_stream_V_keep_V_U_apdone_blk)
);

fmcw_ramp_gen_regslice_both #(
    .DataWidth( 4 ))
regslice_both_dac_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(dac_stream_TVALID_int_regslice),
    .ack_in(regslice_both_dac_stream_V_strb_V_U_ack_in_dummy),
    .data_out(dac_stream_TSTRB),
    .vld_out(regslice_both_dac_stream_V_strb_V_U_vld_out),
    .ack_out(dac_stream_TREADY),
    .apdone_blk(regslice_both_dac_stream_V_strb_V_U_apdone_blk)
);

fmcw_ramp_gen_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dac_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(xor_ln43_fu_165_p2),
    .vld_in(dac_stream_TVALID_int_regslice),
    .ack_in(regslice_both_dac_stream_V_last_V_U_ack_in_dummy),
    .data_out(dac_stream_TLAST),
    .vld_out(regslice_both_dac_stream_V_last_V_U_vld_out),
    .ack_out(dac_stream_TREADY),
    .apdone_blk(regslice_both_dac_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        sync_trigger_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            if ((enable == 1'd1)) begin
                sync_trigger_preg <= xor_ln43_fu_165_p2;
            end else if ((enable_read_read_fu_76_p2 == 1'd0)) begin
                sync_trigger_preg <= 1'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((enable_read_read_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        current_val <= min_val;
    end else if (((enable_read_reg_192 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        current_val <= select_ln43_reg_206;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        enable_read_reg_192 <= enable;
        select_ln43_reg_206 <= select_ln43_fu_179_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((enable_read_reg_192 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (enable == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        dac_stream_TDATA_blk_n = dac_stream_TREADY_int_regslice;
    end else begin
        dac_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((enable == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        dac_stream_TVALID_int_regslice = 1'b1;
    end else begin
        dac_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        if ((enable == 1'd1)) begin
            sync_trigger = xor_ln43_fu_165_p2;
        end else if ((enable_read_read_fu_76_p2 == 1'd0)) begin
            sync_trigger = 1'd0;
        end else begin
            sync_trigger = sync_trigger_preg;
        end
    end else begin
        sync_trigger = sync_trigger_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln43_fu_149_p2 = (zext_ln43_fu_141_p1 + zext_ln43_1_fu_145_p1);

assign add_ln49_fu_173_p2 = (current_val + step_size);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((enable == 1'd1) & (dac_stream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2 = ((regslice_both_dac_stream_V_data_V_U_apdone_blk == 1'b1) | ((enable_read_reg_192 == 1'd1) & (dac_stream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dac_stream_TDATA_int_regslice = current_val;

assign dac_stream_TVALID = regslice_both_dac_stream_V_data_V_U_vld_out;

assign enable_read_read_fu_76_p2 = enable;

assign icmp_ln43_fu_159_p2 = ((add_ln43_fu_149_p2 < zext_ln43_2_fu_155_p1) ? 1'b1 : 1'b0);

assign select_ln43_fu_179_p3 = ((xor_ln43_fu_165_p2[0:0] == 1'b1) ? min_val : add_ln49_fu_173_p2);

assign xor_ln43_fu_165_p2 = (icmp_ln43_fu_159_p2 ^ 1'd1);

assign zext_ln43_1_fu_145_p1 = step_size;

assign zext_ln43_2_fu_155_p1 = max_val;

assign zext_ln43_fu_141_p1 = current_val;


reg find_kernel_block = 0;
// synthesis translate_off
`include "fmcw_ramp_gen_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fmcw_ramp_gen

